# Generated by Django 4.0.4 on 2022-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('company_en', models.CharField(blank=True, max_length=100, null=True)),
                ('company_ja', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_ko', models.CharField(max_length=255)),
                ('tag_en', models.CharField(max_length=255)),
                ('tag_ja', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
