# Generated by Django 4.0.4 on 2022-05-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_ja',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_ko',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag_ja',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag_ko',
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.language')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'company_name',
            },
        ),
    ]
