# Generated by Django 4.0.4 on 2022-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
