# Generated by Django 4.0.4 on 2022-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='tags',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
