# Generated by Django 4.0.4 on 2022-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyname_tags_language_in_use_alter_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
