# Generated by Django 4.0.4 on 2023-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyname_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
