# Generated by Django 4.0.4 on 2023-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_language_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
