# Generated by Django 4.0.4 on 2023-04-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_language_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='is_active',
        ),
    ]
