# Generated by Django 4.0.4 on 2023-04-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_language_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='test_textfield',
            field=models.TextField(blank=True, null=True),
        ),
    ]
