# Generated by Django 4.0.4 on 2023-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_language_test_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='this_is_test',
            field=models.BooleanField(default=False),
        ),
    ]
