# Generated by Django 4.0.4 on 2023-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_language_this_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='hello_world',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
