name: Notify Migrations

on:
  push:
    branches:
      - production
    paths:
      - '**/migrations/*.py'

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for new migrations
      run: |
        NEW_MIGRATIONS=$(git diff --name-only HEAD~1 HEAD | grep 'migrations' | tr '\n' ',')
        if [ -n "$NEW_MIGRATIONS" ]; then
          ENCODED_NEW_MIGRATIONS=$(echo "$NEW_MIGRATIONS" | base64)
          echo "ENCODED_NEW_MIGRATIONS=$ENCODED_NEW_MIGRATIONS" >> $GITHUB_ENV
        fi

    - name: Decode new migrations
      if: env.ENCODED_NEW_MIGRATIONS != ''
      run: |
        DECODED_NEW_MIGRATIONS=$(echo "${{ env.ENCODED_NEW_MIGRATIONS }}" | base64 --decode)
        echo "DECODED_NEW_MIGRATIONS=$DECODED_NEW_MIGRATIONS" >> $GITHUB_ENV

    - name: Send Slack notification
      if: env.ENCODED_NEW_MIGRATIONS != ''
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "New migrations have been merged: ${{ env.DECODED_NEW_MIGRATIONS }}"
        # Optional: add a step to decode the base64-encoded string
        #   run: echo "${{ env.ENCODED_NEW_MIGRATIONS }}" | base64 --decode
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
